#pragma config(Sensor, dgtl8,  autoany,        sensorDigitalIn)
#pragma config(Sensor, dgtl9,  autofour,       sensorDigitalIn)
#pragma config(Sensor, dgtl10, autored,        sensorDigitalIn)
#pragma config(Sensor, dgtl11, autoblue,       sensorDigitalIn)
#pragma config(Sensor, dgtl12, autocap,        sensorDigitalIn)
#pragma config(Motor,  port1,           leftF,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backwheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightM,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightR,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftM,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightL,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...

  slaveMotor(leftR, leftF);
  slaveMotor(leftM, leftF);
  slaveMotor(rightR,rightF);
  slaveMotor(rightM, rightF);

  motor[rightF] = 0;
  motor[leftF] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void blue_cap(void)
{
	motor(leftF) = 127;
	motor(rightF) = 127;
	delay(500);
	// go forward somewhat
	motor(leftF) = -75;
	motor(rightF) = -75;
	delay(300);
	// back up somewhat to put the tines down
	motor(leftF) = 80;
	motor(rightF) = 80;
	delay(1100);
	// go forward to the cap
	motor(leftF) = -80;
	motor(rightF) = 80;
	delay(450);
	// turn somewhat to move the ball out from under the cap
	motor(leftF) = 45;
	motor(rightF) = -45;
	delay(450);
	// turn back to face the other cap
	motor(leftF) = -100;
	motor(rightF) = -100;
	delay(500);
	// back up to stop touching the cap
	motor(leftF) = 0;
	motor(rightF) = 0;
	// stop so the robot doesn't go crazy
}
void red_cap(void)
{
	motor(leftF) = 127;
	motor(rightF) = 127;
	delay(500);
	// go forward somewhat
	motor(leftF) = -75;
	motor(rightF) = -75;
	delay(300);
	// back up somewhat to put the tines down
	motor(leftF) = 80;
	motor(rightF) = 80;
	delay(1100);
	// go forward to the cap
	motor(leftF) = -80;
	motor(rightF) = 80;
	delay(600);
	// turn somewhat to move the ball out from under the cap
	motor(leftF) = -75;
	motor(rightF) = -75;
	delay(450);
	// back up to stop touching the cap
	motor(leftF) = 0;
	motor(rightF) = 0;
	// stop so the robot doesn't go crazy
}
void any_cap(void)
{
	motor(leftF) = 127;
	motor(rightF) = 127;
	delay(500);
	// go forward somewhat
	motor(leftF) = -75;
	motor(rightF) = -75;
	delay(300);
	// back up somewhat to put the tines down
	motor(leftF) = 75;
	motor(rightF) = 75;
	delay(1000);
	// go forward to the cap
	motor(leftF) = -80;
	motor(rightF) = 80;
	delay(450);
	// turn somewhat to move the ball out from under the cap
	motor(leftF) = 45;
	motor(rightF) = -45;
	delay(450);
	// turn back to face the other cap
	motor(leftF) = -100;
	motor(rightF) = -100;
	delay(500);
	// back up to stop touching the cap
	motor(leftF) = 0;
	motor(rightF) = 0;
	// stop so the robot doesn't go crazy
}
void blue_flag(void)
{
	motor(leftF) = -127;
	motor(rightF) = -127;
	delay(2500);
	// drive backwards to the low flag
	motor(leftF) = 0;
	motor(rightF) = 0;
	// stop so the robot doesn't break anything
}
void red_flag(void)
{
	motor(leftF) = -127;
	motor(rightF) = -127;
	delay(2500);
	// go backwards to the low flag
	motor(leftF) = 127;
	motor(rightF) = 127;
	delay(1000);
	// go forward some
	motor(leftF) = 127;
	motor(rightF) = -127;
	delay(2000);
	// turn to face the cap
	motor(leftF) = 0;
	motor(rightF) = 0;
	// stop so the robot doesn't break anything
}

task autonomous()
{
	if(SensorValue (autoblue) == 0) //needs the digital in port 11
	{
		blue_flag();
	}

	if(SensorValue (autocap) == 0) //needs the digital in port 12
	{
		blue_cap();
	}
	if(SensorValue (autored) == 0)// needs the digital in port 10
	{
		red_flag();
	}
	if(SensorValue (autofour) == 0)// needs the digital in port 9
	{
		red_cap();
	}
	if(SensorValue (autoany) == 0)// needs the digital in port 8
	{
		any_cap();
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	bool spinning = false;
	bool forward  = false;

  while (true)
  {
    motor[rightF] = vexRT[Ch2];
    motor[leftF]= vexRT[Ch3];
    // drivetrain control
    if(vexRT[Btn7U] == 1)
		{
			motor[leftL] = 100;
			motor[rightL] = 100;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[leftL] = -100;
			motor[rightL] = -100;
		}
		else
		{
			motor(leftL) = 17;
			motor(rightL)= 17;
		}
		// control for the lift
		if(vexRT[Btn8U] == 1)
		{
			spinning = true;
			forward = false;
		}
		else if(vexRT[Btn8L] == 1)
		{
			spinning  = false;
		}
		if(vexRT[Btn8D] == 1)
		{
			spinning = true;
			forward = true;
		}

		if(spinning)
		{
			if(forward)
			{
				motor[backwheel] = 127;
			}
			else
			{
				motor[backwheel] = -127;
			}
		}
		if(!spinning)
		{
			motor[backwheel] = 0;
		}
		// control for the flipper going up

  }
  wait1Msec(10);
}
