#pragma config(Motor,  port1,           leftF,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           launcher,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightM,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightR,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftM,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          intake,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...

  slaveMotor(leftR, leftF);
  slaveMotor(leftM, leftF);
  slaveMotor(rightR,rightF);
  slaveMotor(rightM, rightF);

  motor[rightF] = 0;
  motor[leftF] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{


  while (true)
  {
    motor[rightF] = vexRT[Ch2];
    motor[leftF]= vexRT[Ch3];
    // drivetrain control
    if(vexRT[Btn7U] == 1)
		{
			motor[leftL] = 100;
			motor[rightL] = 100;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[leftL] = -100;
			motor[rightL] = -100;
		}
		else
		{
			motor(leftL) = 17;
			motor(rightL)= 17;
		}
		// control for the lift
		if(vexRT[Btn6U] == 1)
		{
			motor(launcher) = 100;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor(launcher) = -100;
		}
		else
		{
			motor(launcher) = 17;
		}
		//control for the shooter
		if(vexRT[Btn8L] == 1)
		{
			motor(intake) = 127;
		}
		else if(vexRT[Btn8R] == 1)
		{
			motor(intake) = -127;
		}
		else
		{
			motor(intake) = 0;
		}
		// control for the intake
  }
}
